"""Plot the four-panel MiniBatchKMeans runtime heatmap.

The script consumes the median summary generated by
``profile_discrete_minibatch_kmeans.py``.  The first three panels show seconds
spent in clustering, optimized overlap scoring, and other residual work.  The
fourth panel is categorical: each cell is colored by whichever component has
the largest median time for that sample/dimension pair.
"""

from __future__ import annotations

import argparse
import csv
import os
from pathlib import Path
from typing import Iterable

os.environ.setdefault("MPLCONFIGDIR", str(Path("/tmp") / "matplotlib-overlapindex"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm, ListedColormap
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SUMMARY = ROOT / "artifacts" / "profiling" / "discrete_minibatch_kmeans" / "profile_summary.csv"
DEFAULT_OUTPUT = ROOT / "artifacts" / "profiling" / "discrete_minibatch_kmeans" / "runtime_heatmaps.png"

COMPONENTS = (
    ("clustering_seconds", "Clustering", "#3465a4"),
    ("overlap_scoring_seconds", "Overlap scoring", "#c64630"),
    ("other_seconds", "Other fit work", "#5c4b8a"),
)


def _read_summary(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError(f"Summary file is empty: {path}")
    required = {"n_samples", "n_dimensions"}
    required.update(f"median_{column}" for column, _, _ in COMPONENTS)
    missing = sorted(required.difference(rows[0]))
    if missing:
        raise ValueError(f"Summary file is missing columns: {', '.join(missing)}")
    return rows


def _matrix(
    rows: Iterable[dict[str, str]],
    column: str,
    samples: tuple[int, ...],
    dimensions: tuple[int, ...],
) -> np.ndarray:
    sample_index = {value: i for i, value in enumerate(samples)}
    dimension_index = {value: i for i, value in enumerate(dimensions)}
    matrix = np.full((len(samples), len(dimensions)), np.nan, dtype=float)
    for row in rows:
        n_samples = int(row["n_samples"])
        n_dimensions = int(row["n_dimensions"])
        if n_samples not in sample_index or n_dimensions not in dimension_index:
            continue
        matrix[sample_index[n_samples], dimension_index[n_dimensions]] = float(row[column])
    return matrix


def _annotate(
    ax,
    matrix: np.ndarray,
    *,
    categorical: bool = False,
    categorical_labels: tuple[str, ...] = (),
) -> None:
    """Annotate every finite heatmap cell with a compact value or label."""

    for row_index in range(matrix.shape[0]):
        for column_index in range(matrix.shape[1]):
            value = matrix[row_index, column_index]
            if not np.isfinite(value):
                continue
            if categorical:
                index = int(value)
                text = categorical_labels[index] if index < len(categorical_labels) else str(index)
            else:
                text = f"{value:.3g}"
            ax.text(
                column_index,
                row_index,
                text,
                ha="center",
                va="center",
                fontsize=7.5,
                color="white",
            )


def _style_axes(ax, samples: tuple[int, ...], dimensions: tuple[int, ...]) -> None:
    ax.set_xticks(np.arange(len(dimensions)), labels=[str(v) for v in dimensions])
    ax.set_yticks(np.arange(len(samples)), labels=[str(v) for v in samples])
    ax.set_xlabel("Feature dimensions")
    ax.set_ylabel("Samples")
    ax.tick_params(axis="both", labelsize=8)


def build_figure(summary_path: Path, output_path: Path) -> None:
    """Build and save the 2-by-2 timing/dominance heatmap figure."""

    rows = _read_summary(summary_path)
    samples = tuple(sorted({int(row["n_samples"]) for row in rows}))
    dimensions = tuple(sorted({int(row["n_dimensions"]) for row in rows}))
    matrices = {
        column: _matrix(
            rows,
            f"median_{column}",
            samples,
            dimensions,
        )
        for column, _, _ in COMPONENTS
    }

    fig, axes = plt.subplots(2, 2, figsize=(13.8, 10.4), constrained_layout=True)
    image_axes = (axes[0, 0], axes[0, 1], axes[1, 0])
    for ax, (column, title, color) in zip(image_axes, COMPONENTS):
        matrix = matrices[column]
        # A sequential map per component keeps each panel readable even when
        # clustering and scoring differ by orders of magnitude.  Keep zero or
        # negative residuals visible with a linear scale and a shared neutral
        # low color; negative residuals are possible only from clock noise.
        cmap = plt.get_cmap("magma").copy()
        cmap.set_bad("#eeeeee")
        image = ax.imshow(matrix, origin="lower", aspect="auto", cmap=cmap)
        _style_axes(ax, samples, dimensions)
        ax.set_title(f"{title} time (median seconds)", fontweight="bold")
        _annotate(ax, matrix)
        colorbar = fig.colorbar(image, ax=ax, pad=0.02, fraction=0.046)
        colorbar.ax.set_ylabel("Seconds", rotation=270, labelpad=13)
        colorbar.ax.tick_params(labelsize=8)

    stack = np.stack([matrices[column] for column, _, _ in COMPONENTS], axis=0)
    dominance = np.full(stack.shape[1:], np.nan)
    finite = np.all(np.isfinite(stack), axis=0)
    dominance[finite] = np.argmax(stack[:, finite], axis=0)

    dominance_ax = axes[1, 1]
    dominance_cmap = ListedColormap([color for _, _, color in COMPONENTS])
    dominance_cmap.set_bad("#eeeeee")
    dominance_norm = BoundaryNorm(np.arange(-0.5, len(COMPONENTS) + 0.5, 1), dominance_cmap.N)
    image = dominance_ax.imshow(
        np.ma.masked_invalid(dominance),
        origin="lower",
        aspect="auto",
        cmap=dominance_cmap,
        norm=dominance_norm,
    )
    _style_axes(dominance_ax, samples, dimensions)
    dominance_ax.set_title("Dominant component (median time)", fontweight="bold")
    _annotate(dominance_ax, dominance, categorical=True, categorical_labels=("C", "S", "O"))
    colorbar = fig.colorbar(
        image,
        ax=dominance_ax,
        pad=0.02,
        fraction=0.046,
        ticks=np.arange(len(COMPONENTS)),
    )
    colorbar.ax.set_yticklabels([title for _, title, _ in COMPONENTS])
    colorbar.ax.tick_params(labelsize=8)

    fig.suptitle(
        "Discrete OverlapIndex MiniBatchKMeans runtime profile",
        fontsize=16,
        fontweight="bold",
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=180, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved runtime heatmaps to {output_path}")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, default=DEFAULT_SUMMARY)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    build_figure(args.summary.resolve(), args.output.resolve())
